### ISSUE TITLE
Nouvelles fonctionnalités sur le Plugin

### ISSUE THREAD

**Issue by isagarran** [mika-nt28/Jeedom-CaveVin#1]
Est-il possible de penser à améliorer la cinématique ? 
- Un menu déroulant pour les types de vin (plus il y a de vin, plus le casier est en bas de la page et s'éloigne de la description)
- Les casiers sur la même page, c'est un peu pénible d'aller sur le menu contextuel (pour avoir le bon casier)
- Après l'ajout d'une bouteille, rester sur le casier en cours si possible
- Les Refresh pourraient-ils être automatiques ?
Si je peux aider modestement ... :)

**Comment by mika-nt28** [comment]
_Un menu déroulant pour les types de vin (plus il y a de vin, plus le casier est en bas de la page et s'éloigne de la description)_
J'ai imposé une taille maximal a la liste avec un ascenseur.
Pour facilité la recherche dans cette liste il y a les filtres
_Les casiers sur la même page, c'est un peu pénible d'aller sur le menu contextuel (pour avoir le bon casier)_
Je n'ai pas compris ce que tu veux dire ici
_Après l'ajout d'une bouteille, rester sur le casier en cours si possible_
Je vais réfléchir a comment prendre cette remarque en compte
_Les Refresh pourraient-ils être automatiques ?_
J'ai mis un refresh sur la liste de selection de nos vin ainsi qu'un refresh du widget apres affectation

**Comment by isagarran** [comment]
Hello,
Je ne sais pas comment tu peux faire aussi vite ... 
J'ai défini dans mon cas trois casiers. Lorsque j'affiche la page d'accueil, souvent ce n'est pas le bon casier que je veux voir. Je ne peux pas cliquer sur la bouteille pour faire apparaitre la fiche correspondante.Donc je fais passer ma sourie à gauche pour faire apparaître le menu contextuel de Jeedom. Je vois apparaître mes trois casiers et je sélectionne le bon. Dès que je fais un refresh, je dois recommencer. D'ou ma seconde demande. Eviter les refresh, car je reviens sur le casier de départ et je dois refaire la manipulation pour accéder à la bouteille.
Merci

**Comment by mika-nt28** [comment]
Ok les refresh automatique doivent déjà corrigé ce deuxième problème.
Pour le premier, par défaut on affiche tous les casiers qui permet une utilisation complète des la première page.

**Comment by isagarran** [comment]
Bonjour,
Tu veux que je participes aux tests ? Il y a une procédure ?
D'autre part, lors de la mise à jour, est-ce que je dois faire une quelconque sauvegarde de ma base de données auparavant ?
Cordialement,

**Comment by mika-nt28** [comment]
J'ai validé que les modif ne fonctionne et passé la version en stable.
Peut tu juste confirmé que toute est pris en compte ou qu'il faille apporter d'autre modification
