### ISSUE TITLE
Ajout de popup pour lire le contenu des champs

### ISSUE THREAD

**Issue by isagarran** [mika-nt28/Jeedom-CaveVin#2]
Bonjour,
Ma demande consiste à avoir une popup lorsque le curseur passe au dessus d'un champ ou quelque chose de ce style. Le problème vient que dès que le contenu est plus grand que le champ, il faut cliquer sur Modifier et ensuite aller sur  le champ et faire défiler le texte. Ce n'est quère pratique.
Merci

**Comment by mika-nt28** [comment]
Je n'ai pas bien compris ce que tu veux

**Comment by isagarran** [comment]
Bonjour,
Par exemple, sur le champ "vinification" je rentre : "Une fois récoltés, les raisins sont directement pressés. La fermentation est conduite à basse température pendant 3 semaines pour préserver les arômes." 
Donc je peux rentrer l'information mais pour la visualiser c'est très difficile, il faut cliquer sur modifier en haut à gauche. Puis ensuite aller sur le champ, le sélectionner et avec la flèche droite, faire dérouler le texte pour le lire.
Je ne sais pas comment le faire mais j'ai déjà vu ailleurs qu'il est possible de faire apparaître le contenu du champ en survolant la zone en question. Ça permettrait ainsi de ne pas cliquer sur modifier et de quand même voir le contenu des champs.
Merci et Bonne année 2017

**Comment by mika-nt28** [comment]
Ok je comprend ce que tu veux.
Je met ca en place pour la prochaine version
